[grid]
# id_ablation_type_by_modality = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
# id_ablation_type_by_modality = [0]
# id_ablation_type_by_component =  [0, 1, 2, 3, 4, 5, 6, 7]
# id_ablation_type_by_component =  [6]
single_task_target = ["emo", "pkl"]
single_task_id = [0,1,2] # для emo   → 0,1  ; для pkl   → 0,2

[defaults]
hidden_dim = 512
# mamba_d_state = 6
# mamba_layer_number = 4
# pers_loss_type = 'rmse_gl'
