[grid]
hidden_dim            = [256, 512]
dropout               = [0.15]
out_features          = [128]
num_transformer_heads = [4]
tr_layer_number       = [1]
lr                    = [1e-4]
per_activation        = ['sigmoid']
pers_loss_type        = ["ccc"]
positional_encoding   = [true]
# mamba_d_state         = [8]
# mamba_layer_number    = [1]
# scheduler_type        = ["plateau", "cosine", "onecycle", "huggingface_cosine_with_restarts", "huggingface_cosine", "huggingface_linear"]
# pers_loss_type        = ["mae", "mse", "rmse", "rmse_bell", "rmse_logcosh", "bell", "logcosh", "rmse_bell_logcosh","bell_logcosh", "gl","bell_logcosh_gl", "rmse_gl", "rmse_bell_gl", "bell_gl", "logcosh_gl"] 

[defaults]
hidden_dim = 512
mamba_d_state = 6
mamba_layer_number = 4
pers_loss_type = 'rmse_gl'