[grid]
hidden_dim            = [256, 512]
num_transformer_heads = [2, 4, 8]
dropout = [0.1, 0.15, 0.2]
lr      = [1e-4, 1e-5]


[defaults]
hidden_dim = 512
# mamba_d_state = 6
# mamba_layer_number = 4
# pers_loss_type = 'rmse_gl'
