[grid]
hidden_dim            = [256, 512]
mamba_d_state         = [6, 8, 10, 12]
mamba_layer_number    = [1, 2, 3, 4]
dropout               = [0.15]
# scheduler_type        = ["plateau", "cosine", "onecycle", "huggingface_cosine_with_restarts", "huggingface_cosine", "huggingface_linear"]
# pers_loss_type        = ["ccc", "mae", "mse", "rmse", "rmse_bell", "rmse_logcosh", "bell", "logcosh", "rmse_bell_logcosh","bell_logcosh", "gl","bell_logcosh_gl", "rmse_gl", "rmse_bell_gl", "bell_gl", "logcosh_gl"] 
# pers_loss_type          = ["mae"]
# num_transformer_heads = [8, 16, 32]
# tr_layer_number       = [1, 2, 3, 4]
out_features          = [128, 256]

[defaults]
hidden_dim = 512
mamba_d_state = 6
mamba_layer_number = 4
pers_loss_type = 'rmse_gl'